function [choice,value] = mydialog
    d = dialog('Position',[840 800 250 200],'Name','Instructions');

    txt = uicontrol('Parent',d,...
               'Style','text',...
               'Position',[20 120 210 40],...
               'String','Select which Battery (i.e. Battery 023, or Internal Use Only 003) and the Charge in mAh');
    
    popup = uicontrol('Parent',d,...
               'Style','popup',...
               'Position',[75 90 100 25],...
               'String',{'b001';'b002';'b003'},...
               'Callback',@popup_callback);
           
    text = uicontrol('Parent',d,...
                    'Style','text',...
                    'Position',[75 50 100 40],...
                    'String','Enter Charge (mAh)');
                    
                
    sld = uicontrol('Parent',d,...
                    'Style','edit',...
                    'Position',[75 40 100 20],...
                    'Callback',@chargevalue);

    btn = uicontrol('Parent',d,...
               'Position',[75 00 100 25],...
               'String','Close',...
               'Callback','delete(gcf)');
    choice = 'b001';
   
    
     uiwait(d);
    
    function popup_callback(popup,callbackdata)
        idx = popup.Value;
        popup_items = popup.String;
        choice = char(popup_items(idx,:));
    end
    
    function chargevalue(sld,callbackdata)
        value = sld.String;
    end
   
    
end