function [savefile] = savefunction
d = dialog('Position',[840 800 150 120],'Name','SaveFile');

    txt = uicontrol('Parent',d,...
               'Style','text',...
               'Position',[25 60 110 40],...
               'String','Save File or no?');
    btn  = uicontrol('Parent',d,...
               'Position',[10 20 40 25],...
               'String','Yes',...
               'Callback',@yes);
    btn2 = uicontrol('Parent',d,...
               'Position',[100 20 40 25],...
               'String','No',...
               'Callback',@no);
           
           
           uiwait(d);
           
    function no(btn2,callbackdata)
        savefile = 0;         
        delete(gcf);    
    end
function yes(btn,callbackdata)
        savefile = 1;
        delete(gcf);    
    end
end
