function [plotter] = wanttoplot
d = dialog('Position',[840 800 150 120],'Name','Want to plot');

    txt = uicontrol('Parent',d,...
               'Style','text',...
               'Position',[30 60 100 40],...
               'String','Want To Plot?');
    btn  = uicontrol('Parent',d,...
               'Position',[10 20 40 25],...
               'String','Yes',...
               'Callback',@yes);
    btn2 = uicontrol('Parent',d,...
               'Position',[100 20 40 25],...
               'String','No',...
               'Callback',@no);
           
           
           uiwait(d);
           
    function no(btn2,callbackdata)
        plotter = 0;         
        delete(gcf);    
    end
function yes(btn,callbackdata)
        plotter = 1;
        delete(gcf);    
    end
end