%% Plot Selector

availableplots = { 
    'RSSI' ,...
    'Velocities', ...
    'Positions', ...
    'Att_Con', ...
    'Mag', ...
    'Attitude', ...
    'Throttles', ...
    'Temps', ...
    'BMS', ...
    'Overlay Plot', ...
    'Gyro_Accel', ...
    'Baro & GPS', ...
    'Heading Plot', ...
    'CPU', ...
    'GPS PVT', ...
    };
                   


[selection, ok] = listdlg('ListString',availableplots,'SelectionMode','multi','Name','Plot Selector','PromptString','Select a Plot');





